id: opecha:P007891
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB5978
  title: གྲུབ་བརྙེས་ཀྱི་རྣལ་འབྱོར་པ་ཆེན་མོ་རིན་ཆེན་ཆོས་དབྱིངས་རྡོ་རྗེ་མཆོག་གི་ཞལ་གསུང་ཕྱོགས་བསྒྲིགས་
  volume: ''
  author: ''
