id: P007891
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB5978
  title: གྲུབ་བརྙེས་ཀྱི་རྣལ་འབྱོར་པ་ཆེན་མོ་རིན་ཆེན་ཆོས་དབྱིངས་རྡོ་རྗེ་མཆོག་གི་ཞལ་གསུང་ཕྱོགས་བསྒྲིགས་
  author: ''
  volumes:
    ca2b7a96babb49ffb96e57e829ea0e07:
      image_group_id: I1PD27503
      title: ''
      volume_number: 1
      total_pages: 345
ebook_metadata:
  title: གྲུབ་བརྙེས་ཀྱི་རྣལ་འབྱོར་པ་ཆེན་མོ་རིན་ཆེན་ཆོས་དབྱིངས་རྡོ་རྗེ་མཆོག་གི་ཞལ་གསུང་ཕྱོགས་བསྒྲིགས་
  author: ''
  sku: P007891
  cover: cover.jpg
  layers:
  - pagination
